lst=[1,2,33,"Manish",-10,12.5,True]
print(lst)
print(lst[4])
print(lst[2:6])
print(len(lst))
print(lst*3)

#removie append delete
lst.append(40)
print(lst)
lst.remove("Manish")
print(lst)
del(lst[2])
print(lst)
lst.sort()
print(lst)
lst.sort(reverse=True)
print(lst)
lst.insert(3,99)
print(lst)
print(max(lst))
print(min(lst))
lst.clear()
print(lst)